services:

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: dice
      POSTGRES_USER: dice
      POSTGRES_PASSWORD: dice

    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

    restart: unless-stopped

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dice -d dice"]
      interval: 5s
      timeout: 5s
      retries: 10

    logging:
      driver: awslogs
      options:
        awslogs-region: us-west-2
        awslogs-group: /dice-roller/app
        awslogs-stream: database

  backend:
    image: kornelmk/dice-roller-backend:${APP_VERSION:-latest}

    environment:
      APP_VERSION: ${APP_VERSION:-dev}

    depends_on:
      db:
        condition: service_healthy

    restart: unless-stopped

    logging:
      driver: awslogs
      options:
        awslogs-region: us-west-2
        awslogs-group: /dice-roller/app
        awslogs-stream: backend

  frontend:
    image: kornelmk/dice-roller-frontend:${APP_VERSION:-latest}

    depends_on:
      - backend

    restart: unless-stopped

    logging:
      driver: awslogs
      options:
        awslogs-region: us-west-2
        awslogs-group: /dice-roller/app
        awslogs-stream: frontend

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

    logging:
      driver: awslogs
      options:
        awslogs-region: us-west-2
        awslogs-group: /dice-roller/app
        awslogs-stream: nginx

volumes:
  db_data: