name: Infra CI (Terraform)

permissions:
  id-token: write
  contents: read

on:
  repository_dispatch:
    types: [deploy-infra]

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::392789866533:role/dice-roller-github-actions-role
          aws-region: us-west-2

      - name: Set image version
        run: |
          echo "APP_VERSION=${{ github.event.client_payload.image_tag }}" >> $GITHUB_ENV

      - name: Fail if version missing
        run: |
          if [ -z "$APP_VERSION" ]; then
            echo "APP_VERSION is empty!"
            exit 1
          fi

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan -var="app_version=${APP_VERSION}"

      - name: Terraform Apply with update variables
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan