name: Infra CI (Terraform)

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      image_tag:
        required: true
        type: string
  push:
    branches:
      - main
      - develop
    paths:
      - "infra/**"
      - ".github/workflows/infra.yml"

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::392789866533:role/dice-roller-github-actions-role
          aws-region: us-west-2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply with update variables
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan -var="app_version=${{ steps.meta.outputs.image_tag }}"